export enum ChartDataActionConstants {
  GET_TIME_CHART_DATA_REQUEST_START = 'GET_TIME_CHART_DATA_REQUEST_START',
  GET_TIME_CHART_DATA_REQUEST_FAILED = 'GET_TIME_CHART_DATA_REQUEST_FAILED',
  GET_TIME_CHART_DATA_REQUEST_SUCCESS = 'GET_TIME_CHART_DATA_REQUEST_SUCCESS',
  GET_DEPTH_CHART_DATA_REQUEST_START = 'GET_DEPTH_CHART_DATA_REQUEST_START',
  GET_DEPTH_CHART_DATA_REQUEST_FAILED = 'GET_DEPTH_CHART_DATA_REQUEST_FAILED',
  GET_DEPTH_CHART_DATA_REQUEST_SUCCESS = 'GET_DEPTH_CHART_DATA_REQUEST_SUCCESS'
}
